# Generated by Django 3.1.3 on 2020-11-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='contributor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='email_contributor',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Author"s email'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='exit', max_length=17, verbose_name='ISBN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_due',
            field=models.DateField(blank=True, null=True, verbose_name='ISBN Due'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_received',
            field=models.DateField(blank=True, null=True, verbose_name='ISBN received'),
        ),
        migrations.AddField(
            model_name='book',
            name='print_partner',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ITBRICKS'), (2, 'LULU'), (3, 'AMAZON')], default=1, verbose_name='Print Partner'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publicate on'),
        ),
    ]
